#!/bin/sh

# 'vim <file>' or 'emacs <file>' should use system editor
alias vim="$EDITOR" \
      emacs="$EDITOR"

# doas over sudo
alias sudo=doas

# nsxiv - because why would we keep using that name?
alias sxiv=nsxiv

# verbose - list files to change; interactive - warn before large change
alias cp="cp -iv" \
      mv="mv -iv" \
      rm="rm -vI" \
      mkdir="mkdir -pv"

# commonly used args
alias bc="bc -ql" \
      ffmpeg="ffmpeg -hide_banner"

# use colors
alias ls="ls -hN --color=auto --group-directories-first" \
      grep="grep --color=auto"
