#!/bin/zsh

# Runs once on login shell

# Simple environment variables
export EDITOR="emacsclient -c -a 'emacs'"
export TERMINAL="st"
export BROWSER="firefox"

# XDG default dirs
export XDG_CONFIG_HOME="$HOME/repos/dotfiles/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_MUSIC_DIR="$HOME/music"

# Config file directories
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"

# Program settings
export LESSHISTFILE="-"

# Add `~/.local/bin` to $PATH
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
